# Generated by Django 5.0.4 on 2024-04-15 00:45

import django.db.models.deletion
import src.app.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('user_id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='Número de Identificación')),
                ('first_name', models.CharField(max_length=30, verbose_name='Primer Nombre')),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Nombre')),
                ('last_name', models.CharField(max_length=30, verbose_name='Primer Apellido')),
                ('second_last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Apellido')),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono de Contacto')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ciudad')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Usuario Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Usuario parte del Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superusuario')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', src.app.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(blank=True, max_length=30, null=True, verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_student_worker', models.BooleanField(default=False, verbose_name='Es monitor estudiantil')),
                ('number_of_tickets', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Número de Tiquetes')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
    ]
