name: Django Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.6
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        flake8

    - name: Coverage report
      run: |
        pytest --cov=.
    
    - name: Django testing
      run: |
        pytest
